# Assignments

Below are the due dates for the assignments, as well as links to the RMD and PDF files for each assignment. The due dates may change at the instructor's discretion. Any revised due dates will be announced in class and posted to the website.

<br />


<!-- <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 03-10-2021]*</span> -->

<table class="table">

<thead>
<tr>
<th style="width:50%;">Assignment</th>
<th style="width:15%;">Due Date (T/R)</th>
<th style="width:15%;">Due Date (M/W)</th>
<th style="width:10%;text-align:center">RMD</th>
<th style="width:10%;text-align:center">HTML</th>
</tr>
</thead>

<tbody>

<tr>
<td>Assignment \#1: *Introduction to R Markdown* <br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for this assignment is flexible]*</span></td>
<td>Feb. 01</td>
<td>Feb. 02</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-01-introduction-to-r-markdown.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-01-introduction-to-r-markdown.html)
</td>
</tr>


<tr>
<td>Assignment \#2: *Probability Distributions*<br />
  <span style="margin-left:5px; color:#5a067d;font-size:12px;">*[The due date for Question 11 is flexible]*</span></td>
<td>Feb. 10</td>
<td>Feb. 14</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-02-probability-distributions.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-02-probability-distributions.html)
</td>
</tr>


<tr>
<td>Assignment \#3: *Information Criteria and Model Selection*<br /><span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 02-08-2022]*</span></td>
<td>Mar. 01</td>
<td>Mar. 02</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-03-evidence-and-model-selection.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-03-evidence-and-model-selection.html)
</td>
</tr>


<tr>
<td>Assignment \#4: *Polynomial Effects*</td>
<td>Mar. 17</td>
<td>Mar. 24</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-04-polynomial-effects.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-04-polynomial-effects.html)
</td>
</tr>


<tr>
<td>Assignment \#5: *Logarithmic Transformations*<br /><span style="margin-left:5px; color:#5a067d;font-size:12px;">*[Updated: 03-24-2022]*</span></td>
<td>Mar. 29</td>
<td>Mar. 30</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-05-logarithmic-transformations.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-05-logarithmic-transformations.html)
</td>
</tr>


<tr>
<td>Assignment \#6: *Logistic Regression*</td>
<td>Apr. 12</td>
<td>Apr. 13</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-06-logistic-regression.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-06-logistic-regression.html)
</td>
</tr>


<tr>
<td>Assignment \#7: *LMER: Unconditional Longitudinal Models*</td>
<td>Apr. 21</td>
<td>Apr. 25</td>
<td align="center" style="vertical-align:middle;">
[<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s22-assignment-07-lmer-unconditional-longitudinal-models.Rmd)
</td>
<td align="center" style="vertical-align:middle;">
[<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s22-assignment-07-lmer-unconditional-longitudinal-models.html)
</td>
</tr>


<tr>
<!-- <td>Assignment \#8 *Longitudinal Analysis II*</td> -->
<td align="center" style="vertical-align:middle;">All Assignments and Website</td>
<td colspan="2" align="center" style="vertical-align:middle;">May 06<br />(due at 12:00pm)</td>
<td align="center" style="vertical-align:middle;">
<!-- [<span class="fab fa-markdown" style="color: #ff2600; font-size: 20px;"></span>](https://raw.githubusercontent.com/zief0002/epsy-8252/master/docs/assignments/s21-assignment-08-logistic-regression.Rmd) -->
</td>
<td align="center" style="vertical-align:middle;">
<!-- [<span class="fas fa-link" style="color: #ff2600; font-size: 20px;"></span>](https://zief0002.github.io/epsy-8252/assignments/s21-assignment-08-logistic-regression.html) -->
</td>
</tr>




</tbody>
</table>
